DROP DATABASE spoiler_alert;

-- MySQL Script generated by MySQL Workbench
-- Wed Feb 11 14:09:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spoiler_alert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spoiler_alert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spoiler_alert` DEFAULT CHARACTER SET utf8 ;
USE `spoiler_alert` ;

-- -----------------------------------------------------
-- Table `spoiler_alert`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spoiler_alert`.`User` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `has_premium` TINYINT NOT NULL,
  `free_scans_left` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spoiler_alert`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spoiler_alert`.`Product` (
  `product_id` INT NOT NULL,
  `upc` BIGINT NOT NULL,
  `product_name` VARCHAR(90) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `image_link` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spoiler_alert`.`Recall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spoiler_alert`.`Recall` (
  `recall_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `regions` VARCHAR(255) NOT NULL,
  `amount_sick` INT NOT NULL,
  `amount_dead` INT NOT NULL,
  `product_keywords` VARCHAR(45) NOT NULL,
  `classification` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recall_id`),
  INDEX `fk_Recall_Product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recall_Product`
    FOREIGN KEY (`product_id`)
    REFERENCES `spoiler_alert`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spoiler_alert`.`InventoryItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spoiler_alert`.`InventoryItem` (
  `item_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date_added` DATE NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_InventoryItem_Product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_InventoryItem_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_InventoryItem_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `spoiler_alert`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventoryItem_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spoiler_alert`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
