-- MySQL Script generated by MySQL Workbench
-- Sun Feb  8 14:30:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spoiler_alert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spoiler_alert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spoiler_alert` DEFAULT CHARACTER SET utf8 ;
USE `spoiler_alert` ;

-- -----------------------------------------------------
-- Table `spoiler_alert`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spoiler_alert`.`user` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `has_premium` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
